nodes: 8
tasks_per_node: 8
tag: in1k-16f
eval_name: image_classification_frozen
resume_checkpoint: false
data:
  dataset_name: joy_dataset
  use_aws: 's3://zhangxiaoman_hdd_new/share_data/zhangxiaoman/DATA/Radio_VQA/processed_file/processed_images'
  # root_path: /mnt/petrelfs/linweixiong/jepa/data/joy/
  train_datasets:
    # - /mnt/petrelfs/linweixiong/jepa/data/joy/ForWeixiong/comb_dict.json
    # - /mnt/petrelfs/linweixiong/jepa/data/joy/ForWeixiong/comb_dict_100.json
    - /mnt/petrelfs/linweixiong/jepa/data/joy/ForWeixiong/comb_dict_1000.json
  eval_datasets:
    - /mnt/petrelfs/linweixiong/jepa/data/joy/ForWeixiong/comb_dict_100.json
  labels:
    - /mnt/petrelfs/linweixiong/jepa/data/joy/ForWeixiong/sorted_disease_label_dict.json
    # - /mnt/petrelfs/linweixiong/jepa/data/joy/ForWeixiong/sorted_icd10_label_dict_new.json
  image_folder: ForWeixiong
  num_classes: 5569
  resolution: 224
  target_depth: 64
  crop_size: 64
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
optimization:
  num_epochs: 20
  batch_size: 64
  weight_decay: 0.001
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
pretrain:
  model_name: vit_large
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_sdpa: true
  use_silu: false
  tight_silu: false
  patch_size: 16
  folder: /mnt/petrelfs/linweixiong/jepa/checkpoints
  checkpoint: jepa-latest.pth.tar  # name of pretrained model file inside folder
  write_tag: jepa
